version: '3.1'
services:
  composer:
    image: composer
    volumes:
      - .:/app
    command: [
      'bash', '-c',
      'composer install &&
      if [[ -f /app/.env ]]; then 
        echo ".env file already exists";
      else 
        cp /app/.env.sample /app/.env && php artisan key:generate; 
      fi
      '
    ]

  node:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    command: [
      'bash', '-c',
      "npm install && npm run watch"
    ]
  
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php
      - mariadb
    networks:
      - frontend
    ports:
      - 8000:80

  php:
    build: .dockerconfig/php
    volumes:
      - .dockerconfig/php/conf.d:/user/local/etc/php/conf.d
      - .:/var/www/html
    networks:
      - frontend
      - backend
    expose:
      - 9000

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "moria"
      MYSQL_USER: "johnd"
      MYSQL_PASSWORD: "secret"
    networks:
      - backend
    expose:
      - 3306
    ports:
      - 3306:3306

  cacheserver:
    image: redis
    networks:
      - backend
    expose:
      - 6379
  
networks:
  frontend:
  backend: